### ISSUE TITLE
Add Error Handling to Note Completion

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#26]
```
Select note id for completion: Read floating point storage section in Null book
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    main()
  File "main.py", line 7, in main
    run_menu_loop_mode(database_facade)
  File "/time-management/interface_mode.py", line 40, in run_menu_loop_mode
    map_choice_to_function(choice, facade)
  File "/time-management/interface_mode.py", line 26, in map_choice_to_function
    run_menu_loop_tm(facade)
  File "/time-management/interface_time_management.py", line 29, in run_menu_loop_tm
    map_choice_to_function(choice, facade)
  File "/time-management/interface_time_management.py", line 40, in map_choice_to_function
    complete_task(facade)
  File "/time-management/interface_time_management.py", line 82, in complete_task
    facade.update_completion(row_id)
  File "/time-management/facade.py", line 68, in update_completion
    self.cursor.execute(
sqlite3.OperationalError: near "floating": syntax error
```

**Comment by Straywind** [comment]
What action caused that error?

**Comment by ancbro** [comment]
Now I can't remember - but you can trigger something similar with an alphabetic character - so the exception handling is not very good. Obviously. 
```
Select note id for completion: t
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 8, in main

```

**Comment by Capm96** [comment]
Hey, I'd like to contribute to this problem 👍

**Comment by Straywind** [comment]
Knock yourself out bro
